const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('publisher', {
  listWorkspaces: () => ipcRenderer.invoke('workspaces:list'),
  selectWorkspace: (workspaceId) => ipcRenderer.invoke('workspace:select', workspaceId),
  updateWorkspace: (workspaceId, input) => ipcRenderer.invoke('workspace:update', workspaceId, input),
  listAccounts: () => ipcRenderer.invoke('accounts:list'),
  getBrowserStatus: () => ipcRenderer.invoke('browser:status'),
  openBrowser: (accountId) => ipcRenderer.invoke('browser:open', accountId),
  detectAccount: (accountId) => ipcRenderer.invoke('browser:detect', accountId),
  renameAccount: (accountId, label) => ipcRenderer.invoke('account:rename', accountId, label),
  openAccountFolder: (accountId) => ipcRenderer.invoke('account:open-folder', accountId),
  resetAccount: (accountId) => ipcRenderer.invoke('account:reset', accountId),
  closeBrowser: () => ipcRenderer.invoke('browser:close'),
  chooseVideo: () => ipcRenderer.invoke('file:choose-video'),
  chooseCover: () => ipcRenderer.invoke('file:choose-cover'),
  submitTestPublish: (payload) => ipcRenderer.invoke('test-publish:submit', payload),
  resolveTestPublishId: (input) => ipcRenderer.invoke('test-publish:resolve-id', input),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  saveSettings: (input) => ipcRenderer.invoke('settings:save', input),
  getFeishuBrowserStatus: () => ipcRenderer.invoke('feishu-browser:status'),
  openFeishuBrowser: () => ipcRenderer.invoke('feishu-browser:open'),
  closeFeishuBrowser: () => ipcRenderer.invoke('feishu-browser:close'),
  getLibraryPaths: () => ipcRenderer.invoke('library:paths'),
  listLibraryProducts: (workspaceId, schemeId = 'default') => ipcRenderer.invoke('library:list-products', workspaceId, schemeId),
  listLibrarySchemes: () => ipcRenderer.invoke('library:schemes'),
  saveLibraryScheme: (input) => ipcRenderer.invoke('library:save-scheme', input),
  openLibraryScheme: (schemeId) => ipcRenderer.invoke('library:open-scheme', schemeId),
  inspectLibraryScheme: (schemeId) => ipcRenderer.invoke('library:inspect-scheme', schemeId),
  saveMaterialBatchTemplate: () => ipcRenderer.invoke('library:save-batch-template'),
  importMaterialBatch: (schemeId) => ipcRenderer.invoke('library:import-batch', schemeId),
  chooseLibraryCovers: () => ipcRenderer.invoke('library:choose-covers'),
  saveLibraryProduct: (input) => ipcRenderer.invoke('library:save-product', input),
  exportMaterialPackage: (input) => ipcRenderer.invoke('library:export-package', input),
  importMaterialPackage: () => ipcRenderer.invoke('library:import-package'),
  openLibrary: (key) => ipcRenderer.invoke('library:open', key),
  getCurrentPlan: () => ipcRenderer.invoke('plan:current'),
  getDurationEstimates: () => ipcRenderer.invoke('duration:estimates'),
  listSchedulePolicies: () => ipcRenderer.invoke('schedule-policies:list'),
  saveSchedulePolicy: (input) => ipcRenderer.invoke('schedule-policies:save', input),
  selectSchedulePolicy: (id) => ipcRenderer.invoke('schedule-policies:select', id),
  deleteSchedulePolicy: (id) => ipcRenderer.invoke('schedule-policies:delete', id),
  createPlan: (date, filterMode = 'auto', schemeId = 'auto', schedulePolicyId = 'default') => ipcRenderer.invoke('plan:create', { date, filterMode, schemeId, schedulePolicyId }),
  resolveCommerceTitles: () => ipcRenderer.invoke('plan:resolve-commerce-titles'),
  updatePlanItem: (itemId, input) => ipcRenderer.invoke('plan:update-item', itemId, input),
  setPlanSelection: (itemIds, selected) => ipcRenderer.invoke('plan:set-selection', itemIds, selected),
  confirmUncertain: (itemId, published) => ipcRenderer.invoke('plan:confirm-uncertain', itemId, published),
  choosePlanCover: () => ipcRenderer.invoke('plan:choose-cover'),
  exportPlanIds: () => ipcRenderer.invoke('plan:export-ids'),
  copyPlanIdTable: () => ipcRenderer.invoke('plan:copy-id-table'),
  syncPlanIds: () => ipcRenderer.invoke('plan:sync-ids'),
  openPublishedVideos: () => ipcRenderer.invoke('plan:open-published-videos'),
  openIdRecords: () => ipcRenderer.invoke('plan:open-id-records'),
  executePlan: () => ipcRenderer.invoke('plan:execute'),
  clearCache: () => ipcRenderer.invoke('cache:clear'),
  onAutomationTakeover: (callback) => ipcRenderer.on('automation:takeover', (_event, kind) => callback(kind)),
  onPlanItemState: (callback) => ipcRenderer.on('plan:item-state', (_event, value) => callback(value))
});
